name: 'Receptura akcji Dockera'
description: 'Pozdrów kogoś'
inputs:
  who-to-greet:
  description: 'Kogo pozdrowić'
  required: true
  default: 'świecie'
  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet }}