name: Docker Hello World

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hello-world .

      - name: Run container
        run: docker run --rm hello-world
