name: Akcja CI
on: [push]
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: who-to-greet
              uses: ./
              with:
                  who-to-greet: "@wulfland"